name: Telegraf Syntax Check

on:
  pull_request:
    branches:
      - master

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install flake8
      run: pip install flake8

    - name: Find Python files in PR
      id: findfiles
      run: |
        git fetch origin master
        files="$(git diff --name-only origin/master -- '*.py')"
        echo "files=${files}" >> "$GITHUB_ENV"

    - name: Debug
      run: |
        echo "${{ env.files }}"

    - name: Check Python syntax
      run: |
        files="${{ env.files }}"
        if [[ -n "$files" ]]; then
          echo "$files" | xargs flake8 --show-source --statistics
        else
          echo "No Python files found in the PR."
        fi
