name: Telegraf Syntax Check

on:
  pull_request:
    branches:
      - master

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install flake8
      run: pip install flake8

    - name: Find Python files in PR
      id: find-files
      run: |
        git fetch origin master:refs/remotes/origin/master
        files=$(git diff --name-only $(git merge-base HEAD refs/remotes/origin/master) | grep '.py$')
        if [[ -n $files ]]; then
          echo "FILES=$files" >> $GITHUB_ENV
        fi

    - name: Check Python syntax
      run: |
        files="${{ steps.find-files.outputs.files }}"
        if [ -n "$files" ]; then
          find . -name '*.py' -type f -print0 | xargs -0 flake8 --show-source --statistics
        else
          echo "No Python files found in the PR."
        fi
