name: Telegraf Check Syntax

on:
  pull_request:
    branches:
      - master

jobs:
  check_syntax:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: pip install pylint

    - name: Check Python syntax
      run: |
        python_files=$(git diff --name-only HEAD master | grep '\.py$')
        pylint --min-python-version=${{ matrix.python-version }} $python_files
