name: Syntax Check

on:
  pull_request:
    branches:
      - master

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install flake8
      run: pip install flake8

    - name: Find Python files in PR
      id: find-files
      run: |
        echo "::set-output name=files::$(git diff --name-only HEAD $(git merge-base HEAD master) | grep '.py$')"
        echo "::set-output name=files::$(git diff --name-only HEAD $(git merge-base HEAD master) | grep '.py$')"

    - name: Check Python syntax
      run: |
        files="${{ steps.find-files.outputs.files }}"
        if [ -n "$files" ]; then
          echo "$files" | xargs flake8 --show-source --statistics
        else
          echo "No Python files found in the PR."
